version: '3.8'

services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: biblioteca-postgres
    environment:
      POSTGRES_DB: biblioteca_comunitaria
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 246895
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - biblioteca-network
    restart: unless-stopped

  # Aplicação Spring Boot
  app:
    build: .
    container_name: biblioteca-app
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: biblioteca_comunitaria
      DB_USERNAME: postgres
      DB_PASSWORD: 246895
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin123
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - biblioteca-network
    restart: unless-stopped
    volumes:
      - app_logs:/app/logs

  # Nginx (Proxy reverso)
  nginx:
    image: nginx:alpine
    container_name: biblioteca-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - biblioteca-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  app_logs:
    driver: local

networks:
  biblioteca-network:
    driver: bridge
