spring:
  application:
    name: biblioteca-igreja
  
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 246895
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true
  
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
  
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

server:
  port: 8080

logging:
  level:
    com.biblioteca: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
